chapter2.docx:	chapter2.md chapter2.bib ../reference/reference.docx
	pandoc -o chapter2.docx --filter pandoc-citeproc --reference-doc=../reference/reference.docx chapter2.md

clean:
	rm -i chapter2.docx

