chapter3.docx: chapter3.md ../bib/merged.bib ../reference/draft.docx
	pandoc -o chapter3.docx --filter pandoc-citeproc --reference-doc=../reference/draft.docx chapter3.md

clean:
	rm -i chapter3.docx

