chapter5.docx:	chapter5.md chapter5.bib ../reference/reference.docx
	pandoc -o chapter5.docx --filter pandoc-citeproc --reference-doc=../reference/reference.docx chapter5.md

clean:
	rm -i chapter5.docx

