burrows.docx: burrows.md /Users/ple/Work/Dissertation/ref/draft.docx
	pandoc -o burrows.docx --reference-doc=/Users/ple/Work/Dissertation/ref/draft.docx burrows.md

visualization.docx: visualization.md /Users/ple/Work/Dissertation/ref/draft.docx
	pandoc -o visualization.docx --reference-doc=/Users/ple/Work/Dissertation/ref/draft.docx visualization.md

clean:
	rm -i burrows.docx visualization.docx

